name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: '1.19'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t guiricha/fathom:latest .
      - name: Push Docker image
        run: docker push guiricha/fathom:latest
      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v3
      #   with:
      #     # either 'goreleaser' (default) or 'goreleaser-pro'
      #     distribution: goreleaser
      #     version: latest
      #     args: release --rm-dist -p 1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
